---
title: "A Look Into The Random Forest Algorithm And It's Applications"
author: "Daerian Dilkumar, Guan Yu Chen, Derek Frempong, Zong Li"
date: "April 4, 2018"
document-class: report
header-includes:
  - \usepackage{bbm}
output:
  pdf_document: 
    number_sections: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rpart)
library(rpart.plot)
library(dplyr)
```

\newpage
\tableofcontents
\newpage


\section{Introduction}

This project was aimed at building and using an algorithm that will create predictions for classification and regression problems by using the idea of "random forests." The algorithm heavily relies on the aspect of "randomness" to reduce bias, since it attempts to randomly select sample spaces AND feature spaces from the original data, and does it hundreds of times over. The goal is to then to train a series of models and gain inputs from each, contributing to a final result. The algorithm does best at predicting the regressive variant for quantitative predictions. 

A "random forest" is a collections of decision trees which each perform predictions, after which the forest will aggregate these or select a prediction which it will return. Each tree is trained over a bootstrapepd sample of the   training set, with a randomly selected set of variables to create it's feature space. This means that each tree has high bias, however since the forest is intended for use with hundreds of trees, the bias in the overall forest drops significantly lower than other models for this result.


Bootstrapping is the process by which we create a sample of the original data, which has the same sie as the original data. This is made possible because the sampling is done with replacement. Therefore the same observations can be used repeatedly, with a uniform distribution chance to be chosen.

\section{Methodologies}

The procedure is as follows:
  - Select a number of trees for the forest, and how big the feature space is. 
  $\\$
  - For each tree, choose variables from the feature space, and get a bootsrap. 
  $\\$
  - Train the model for each tree with these variables for the given labels. 
  $\\$
  - Collect the trees into a forest to get them ready for predictions 
  $\\$
  - Finally, given testing data, use the forest to create as many predictions are there are trees.
  $\\$
  - Aggregate the predictions for a final prediction for each observation in the testing data.
  $\\$



\section{Development Process}

\section{Results}

\section{Wrap-Up}

\section{Appendix}
\textsc{Note:} The following libraries are used throughout the code: \texttt{tidyverse}, \texttt{dplyr}, \texttt{rpart}, and \texttt{rpart.plot}.


\section{References}
<!-- in-text: (Gareth, n.d.) -->
Gareth, J. \textit{An Introduction to Statistical Learning: with Applications in R}. Springer.

<!-- in-text: (Hastie, n.d.) -->
Hastie, T. \textit{The elements of statistical learning [electronic resource] : data mining, inference, and prediction} (2nd ed.). Springer.

<!-- in-text: ("Random forest", 2018) -->
\textit{Random forest}. (2018). \textit{En.wikipedia.org}. Retrieved 22 January 2018, from [https://en.wikipedia.org/wiki/Random_forest](https://en.wikipedia.org/wiki/Random_forest)