---
title: "A look into the applications of random forest for the steel dataset"
author: "Zong Li"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Import necessary packages:
```{r, echo = FALSE, message=FALSE, warning=FALSE}
source("randomforest.R")
library(dplyr)
library(tidyverse)
library(rpart)
library(rpart.plot)
set.seed(1)
```

Read data. The parameter names and the data itself is in two separate files;
we need to first read in the data then set set the column names using the file 
containing the parameter names.
```{r, include=FALSE}
data_file <- "Faults.NNA"
headers_file <- "Faults27x7_var.txt"
data <- read.table(data_file, sep = "" , header = F, na.strings ="", 
                   stringsAsFactors= F)
data_headers <- scan(headers_file, what="", sep="\n")
colnames(data) <- data_headers
```

Clean data and make column names string-friendly
```{r, include=FALSE}
#Purge rows containing N/A entries
data <- (data[complete.cases(data),])

# Remove spaces from column names
names(data) = gsub(" ","_", names(data))
```

Split data into training and testing sets with a 7:3 ratio and replacement
```{r, include=FALSE}
split = sample(2, nrow(data), prob=c(0.7,0.3), replace=TRUE)
train_subset = data[split==1,]
test_subset = data[split==2,]
```


```{r, warning=FALSE}
train_labels = as.factor(unlist(train_labels[ncol(train_labels)]))#training_set labels
test_labels = as.factor(unlist(test_labels[ncol(test_labels)]))# testing_set Labels
num_trees = 500
num_something = 3
f = PerformClassification(train_subset,train_labels,test_subset,test_labels,num_trees,num_something,data)
```
